name: "My Podcast Generator"
author: "Oleh"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    desciption: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    desciption: The commiter's name
    required: true
    default: ${{ github.actor }}

